# Generated by Django 4.2.7 on 2023-11-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.TextField(default=3, max_length=100, verbose_name='Описание пиццы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza',
            name='title',
            field=models.TextField(max_length=20, verbose_name='Название пиццы'),
        ),
    ]
