# Generated by Django 4.2.7 on 2023-11-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pizzaorder_delete_delivery_delete_mydatamodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzaorder',
            old_name='pizza_type',
            new_name='pizza_name',
        ),
    ]
