# Generated by Django 4.2.7 on 2023-11-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_categorydel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryDel',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='pizza',
        ),
        migrations.AddField(
            model_name='menu',
            name='list_value',
            field=models.TextField(default=3, max_length=150, verbose_name='Список продуктов'),
            preserve_default=False,
        ),
    ]
